// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iuirndoarleaufakdzsa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml1aXJuZG9hcmxlYXVmYWtkenNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NzgxMzgsImV4cCI6MjA3MDA1NDEzOH0.PSd5FHpcMSGCsDYAkJjEqn7j39Q2JcZZ1SOPmj197Q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});